# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHubAzureDevOpsInfrastructureProvisioningTerraform'
        repository: '465848451629697498456112665444/WeatherAPI'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
- stage: Provision
  dependsOn: Build
  displayName: Terraform on Azure
  jobs: 
    - job: Provision
      displayName: Provisioning Container Instance
      pool:
        vmImage: ubuntu-latest
      variables:
      - group: Az-DevOps-Pipelines
      steps:
      - bash: |
          terraform init \
            -backend-config="storage_account_name=$TF_STATE_BLOB_ACCOUNT_NAME" \
            -backend-config="container_name=$TF_STATE_BLOB_CONTAINER_NAME" \
            -backend-config="key=$TF_STATE_BLOB_FILE" \
            -backend-config="access_key=$TF_STATE_STORAGE_KEY"
        displayName: Terraform Init
        env:
          TF_STATE_BLOB_ACCOUNT_NAME:   $(storage-account-name)
          TF_STATE_BLOB_CONTAINER_NAME: $(container-name)
          TF_STATE_BLOB_FILE:           $(TFstate-File-Name-Azure-DevOps-Infrastructure-Provisioning-with-Terraform)
          TF_STATE_STORAGE_KEY:      $(euterraformstatefile-key-1)
          TF_VARimagebuild: $(tag)   
      - bash: terraform plan -out deployment.tfplan
        displayName: Terraform Plan 
        env:
          ARM_SUBSCRIPTION_ID: $(kv-arm-subscription-id)
          ARM_CLIENT_ID:       $(kv-arm-client-id)
          ARM_CLIENT_SECRET:   $(kv-arm-client-secret)
          ARM_TENANT_ID:       $(kv-arm-tenant-id)
          TF_VARimagebuild: $(tag)
      - bash: terraform apply -auto-approve deployment.tfplan
        displayName: Terraform Apply
        env:
          ARM_SUBSCRIPTION_ID: $(kv-arm-subscription-id)
          ARM_CLIENT_ID:       $(kv-arm-client-id)
          ARM_CLIENT_SECRET:   $(kv-arm-client-secret)
          ARM_TENANT_ID:       $(kv-arm-tenant-id)
          TF_VARimagebuild: $(tag)
